--substitute your own correct values, and run in shell and or put in something like .bash_profile
export EMAIL_AUTH="foo"
export EMAIL_FROM="foo@bar.com"
export EMAIL_HOST_NAME="smtp.foobar.com"
export EMAIL_PORT="25"
export EMAIL_SERVER="foobar62"
export EMAIL_NOREPLY="noreply@foobar.com"
export EMAIL_FROM_NAME="foobar"
export EMAIL_ADMIN="foo@bar.com"
export EMAIL_REPLYTO="bar@barfoo.com"
